// <auto-generated />
using System;
using Coderland_BackEnd_Challenge.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Coderland_BackEnd_Challenge.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Coderland_BackEnd_Challenge.Models.CarBrands", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FoundationYear")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MarcasAutos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryOfOrigin = "Japan",
                            FoundationYear = new DateTime(1937, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            CountryOfOrigin = "USA",
                            FoundationYear = new DateTime(1937, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            CountryOfOrigin = "USA",
                            FoundationYear = new DateTime(1911, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 4,
                            CountryOfOrigin = "Japan",
                            FoundationYear = new DateTime(1933, 12, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 5,
                            CountryOfOrigin = "Germany",
                            FoundationYear = new DateTime(1913, 10, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 6,
                            CountryOfOrigin = "China",
                            FoundationYear = new DateTime(1862, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Changan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
